# Generated by Django 3.2.3 on 2021-05-21 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210520_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('year', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'biographies',
            },
        ),
        migrations.AddField(
            model_name='author',
            name='biography',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.biography'),
        ),
    ]
