# Generated by Django 3.2.3 on 2021-05-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210521_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biography',
            name='year',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
