# Generated by Django 3.2.3 on 2021-05-21 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_biography_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='direction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.direction'),
        ),
    ]
